#!/bin/bash

# This script check ping and show result as simple string
#
# The main idea - copy past or quick modify with new logic
#
# To execute the script, do not forget to set permissions, (linux comand - chmod)


# --- You Configuration ---

# Set the required address
CHECK_HOST="127.0.0.1"

# or created environment variable with name CHECK_HOST 
# and recomment string below
#export CHECK_HOST

# ---


echo "Check $CHECK_HOST ..."
echo
if ping -q -c 1 -s 1 -W 1 $CHECK_HOST > /dev/null 1>&1
then
	# Just add you logic here
	echo "ping ok"	
	exit 1
else
	# Just add you logic here
	echo "ping not ok"	
	exit 0
fi

